; Team VanRossum
; Tests for placement.lisp

(include-book "placement")
(include-book "testing" :dir :teachpacks)

(check-expect (get-row '() 0) nil)

(check-expect (get-row  '((#\e #\n #\b #\c #\d #\r #\t #\b)
			    (#\b #\e #\t #\q #\n #\e #\i #\s)
			    (#\n #\i #\f #\w #\i #\q #\n #\d)
			    (#\y #\q #\w #\y #\m #\w #\s #\o)
			    (#\e #\d #\e #\r #\g #\y #\t #\g)
			    (#\w #\z #\h #\i #\n #\d #\a #\s)
			    (#\e #\c #\m #\h #\g #\m #\c #\b)
			    (#\w #\n #\x #\f #\m #\r #\q #\a)) 3)
              '(#\y #\q #\w #\y #\m #\w #\s #\o))

(check-expect (get-row  '((#\e #\n #\b #\c #\d #\r #\t #\b)
			    (#\b #\e #\t #\q #\n #\e #\i #\s)
			    (#\n #\i #\f #\w #\i #\q #\n #\d)
			    (#\y #\q #\w #\y #\m #\w #\s #\o)
			    (#\e #\d #\e #\r #\g #\y #\t #\g)
			    (#\w #\z #\h #\i #\n #\d #\a #\s)
			    (#\e #\c #\m #\h #\g #\m #\c #\b)
			    (#\w #\n #\x #\f #\m #\r #\q #\a)) 0)
              '(#\e #\n #\b #\c #\d #\r #\t #\b))

(check-expect (get-row '((#\e #\n #\b #\c #\d #\r #\t #\b)
			    (#\b #\e #\t #\q #\n #\e #\i #\s)
			    (#\n #\i #\f #\w #\i #\q #\n #\d)
			    (#\y #\q #\w #\y #\m #\w #\s #\o)
			    (#\e #\d #\e #\r #\g #\y #\t #\g)
			    (#\w #\z #\h #\i #\n #\d #\a #\s)
			    (#\e #\c #\m #\h #\g #\m #\c #\b)
			    (#\w #\n #\x #\f #\m #\r #\q #\a)) 10)
              nil)
(check-expect (update-row '((#\e #\n #\b #\c #\d #\r #\t #\b)
			    (#\b #\e #\t #\q #\n #\e #\i #\s)
			    (#\n #\i #\f #\w #\i #\q #\n #\d)
			    (#\y #\q #\w #\y #\m #\w #\s #\o)
			    (#\e #\d #\e #\r #\g #\y #\t #\g)
			    (#\w #\z #\h #\i #\n #\d #\a #\s)
			    (#\e #\c #\m #\h #\g #\m #\c #\b)
			    (#\w #\n #\x #\f #\m #\r #\q #\a))
                          8 (#\q #\q #\q #\q #\q #\q #\q #\q) 3 0)
              '((#\e #\n #\b #\c #\d #\r #\t #\b)
                (#\b #\e #\t #\q #\n #\e #\i #\s)
                (#\n #\i #\f #\w #\i #\q #\n #\d)
                (#\q #\q #\q #\q #\q #\q #\q #\q)
                (#\e #\d #\e #\r #\g #\y #\t #\g)
                (#\w #\z #\h #\i #\n #\d #\a #\s)
                (#\e #\c #\m #\h #\g #\m #\c #\b)
                (#\w #\n #\x #\f #\m #\r #\q #\a)))
